.gitignore
config.yaml
config/db.js
controllers/health.controllers.js
example.env
middleware/errorMiddleware.js
package-lock.json
package.json
routes/health.routes.js
server.js
utils/handleResponse.js
utils/handleToken.js

project initialization2

---

config/db.js
controllers/auth.controllers.js
models/users.model.js
package-lock.json
package.json
routes/auth.routes.js
routes/health.routes.js
server.mjs
swagger/swagger.js
swagger/swagger_output.json
utils/handleToken.js
utils/logger.js

added swagger doc

---

controllers/auth.controllers.js
middleware/errorMiddleware.js
models/users.model.js
package-lock.json
package.json
server.mjs
utils/handleToken.js

fixed error middleware

---

config/email.js
controllers/auth.controllers.js
package-lock.json
package.json
services/templates.services.js
services/users.services.js

added email service

---

controllers/auth.controllers.js
models/users.model.js
package-lock.json
package.json
routes/auth.routes.js
routes/user.routes.js
services/users.services.js
swagger/swagger_output.json

completed reset password

---

controllers/auth.controllers.js

changes 1234

---

models/categories.model.js
models/products.model.js
models/services.model.js

designed models for service and products

designed models for service and products

---

controllers/admin/admin-categories.controllers.js
controllers/admin/admin-products.controllers.js
controllers/admin/admin-services.controllers.js
models/categories.model.js
models/products.model.js
models/services.model.js
routes/admin/categories.routes.js
routes/admin/products.routes.js
routes/admin/services.routes.js
server.mjs
swagger/swagger_output.json

added admin apis

---

controllers/admin/admin-products.controllers.js
controllers/admin/admin-services.controllers.js
models/products.model.js
models/services.model.js
routes/admin/products.routes.js
server.mjs
swagger/swagger_output.json

modifications 1023

---

middleware/userMiddleware.js
utils/handleToken.js

fixed auth middleware

---

controllers/admin/users.controller.js
models/users.model.js

modified update user

---

models/users.model.js

modified user model

---

controllers/admin/admin-products.controllers.js
models/products.model.js

configured product

---

controllers/admin/admin-services.controllers.js
models/products.model.js
models/services.model.js

model changes

---

controllers/admin/admin-categories.controllers.js
controllers/admin/admin-products.controllers.js
controllers/admin/admin-services.controllers.js
routes/admin/categories.routes.js
routes/admin/products.routes.js
routes/admin/services.routes.js

added image uploading ability

---

controllers/admin/admin-categories.controllers.js
controllers/admin/admin-products.controllers.js
controllers/admin/admin-services.controllers.js
controllers/admin/users.controller.js
swagger/swagger_output.json

added delete from cloudinary

---

controllers/admin/admin-products.controllers.js
controllers/admin/admin-services.controllers.js
controllers/seller/products.seller.controller.js
controllers/seller/services.seller.controller.js
routes/seller/products.seller.routes.js
routes/seller/services.seller.routes.js
swagger/swagger_output.json

fixed service and products

---

controllers/admin/admin-categories.controllers.js
controllers/admin/admin-products.controllers.js
controllers/admin/admin-services.controllers.js
controllers/admin/users.controller.js
controllers/auth.controllers.js
controllers/health.controllers.js
controllers/profile.controllers.js
controllers/seller/products.seller.controller.js
controllers/seller/services.seller.controller.js
swagger/swagger_output.json

added swagger tags

---

controllers/auth.controllers.js
controllers/contactus.controllers.js
controllers/profile.controllers.js
models/contactus.model.js
models/productOrder.model.js
models/serviceOrder.model.js
models/users.model.js
routes/contactus.routes.js
routes/profile.routes.js
server.mjs
swagger/swagger_output.json

update profile page and swagger

update profile page

---

controllers/admin/testimonials.controllers.js
controllers/user/testimonials.controllers.js
models/testimonials.model.js
routes/admin/testimonials.routes.js
routes/user/testimonials.routes.js
server.mjs

Created endpoints for:
- admin get unapproved testimonials
- admin update testimonials
- admin approve testimonials
- admin delete testimonials
- user get approved testimonials
- made minor fix in testimonial model

Admin testimonial

---

controllers/admin/admin-products.controllers.js
controllers/admin/admin-services.controllers.js
controllers/seller/products.seller.controller.js
controllers/seller/services.seller.controller.js

added image update

---

controllers/admin/admin-products.controllers.js
controllers/admin/admin-services.controllers.js
controllers/seller/products.seller.controller.js
controllers/seller/services.seller.controller.js
swagger/swagger_output.json

fixed update image

---

controllers/admin/admin-groupchats.controllers.js
models/groupchat.model.js
routes/admin/groupchat.routes.js
server.mjs

- created groupchats model
- created endpoints for creating groupchats
- created endpoint for listing groupchats an admin created
- created endpoints for deleting, suspending and activating groupchats 
- created an endpoint for updating group chats

New pull request for admin groupchats endpoints

---

controllers/admin/admin-categories.controllers.js
controllers/admin/admin-services.controllers.js
swagger/swagger_output.json

added filter for category and services

added filter for category and services

---

controllers/home.controller.js
routes/home.routes.js
server.mjs

added home

---

controllers/home.controller.js

fixed subcategory search

---

controllers/home.controller.js

change 203

---

routes/home.routes.js

worked on category changes

---

controllers/admin/users.controller.js
controllers/profile.controllers.js
models/users.model.js
routes/profile.routes.js
swagger/swagger_output.json

added company details

---

controllers/admin/admin-order.controllers.js
controllers/user/order.controllers.js
models/productOrder.model.js
routes/admin/orders.routes.js
routes/user/order.routes.js
server.mjs

added order and checkout

---

controllers/admin/admin-order.controllers.js
controllers/user/order.controllers.js
models/productOrder.model.js
models/productOrderPayment.model.js
routes/admin/orders.routes.js
routes/user/order.routes.js
swagger/swagger_output.json

chnaged order system model

---

controllers/seller/orders.seller.controller.js
controllers/user/order.controllers.js
controllers/user/payments.controllers.js
models/productOrderPayment.model.js
routes/seller/orders.seller.routes.js
routes/user/order.routes.js
routes/user/payments.routes.js
server.mjs
swagger/swagger_output.json

worked on orders and payments

---

controllers/admin/admin-payments.controllers.js
controllers/admin/admin-products.controllers.js
controllers/auth.controllers.js
controllers/seller/products.seller.controller.js
models/products.model.js
models/users.model.js
routes/admin/payments.routes.js
server.mjs
swagger/swagger_output.json

I did x find x

---

config.yaml
controllers/user/payments.controllers.js
package-lock.json
package.json
routes/user/payments.routes.js

added payment api

---

controllers/admin/admin-withdrawals.controller.js
controllers/seller/account.seller.controller.js
controllers/seller/withdrawal.seller.controller.js
models/users.model.js
models/withdrawal.model.js
routes/admin/withdrawal.routes.js
routes/seller/account.seller.routes.js
routes/seller/withdrawal.seller.routes.js
server.mjs
swagger/swagger_output.json

backend for withdrawals and account

backend for withdrawals and account

---

controllers/admin/admin-withdrawals.controller.js

withdrawal fixes

---

controllers/user/order.controllers.js
models/productOrder.model.js

model for the order location

---

controllers/seller/account.seller.controller.js
swagger/swagger_output.json

fix withdrawal and updated swagger

fix withdrawal and updated swagger

---

swagger/swagger_output.json

updated swagger

---

controllers/admin/admin-order.controllers.js
controllers/admin/users.controller.js
controllers/profile.controllers.js
models/users.model.js
routes/admin/orders.routes.js
swagger/swagger_output.json

worked on admin user

---

controllers/admin/users.controller.js
controllers/auth.controllers.js
controllers/home.controller.js
controllers/profile.controllers.js
controllers/user/order.controllers.js
controllers/user/products.controllers.js
controllers/user/services.controllers.js
swagger/swagger_output.json

fixes 20202

---

controllers/profile.controllers.js
controllers/seller/analysis.seller.controller.js
controllers/seller/orders.seller.controller.js
controllers/seller/products.seller.controller.js
routes/profile.routes.js
routes/seller/analysis.seller.routes.js
server.mjs
swagger/swagger_output.json
utils/selectMonth.js

added seller data analysis

---

controllers/auth.controllers.js
controllers/user/kyc.controllers.js
models/users.model.js
swagger/swagger_output.json

completed kyc for the website

---

controllers/home.controller.js
controllers/profile.controllers.js

fixed product details search

---

controllers/seller/products.seller.controller.js
controllers/seller/services.seller.controller.js
utils/checkIfJsonOrString.js

fixed string to map

---

controllers/chats/chat.controllers.js
controllers/chats/messages.controllers.js
controllers/notifications.controller.js
controllers/user/order.controllers.js
routes/user/order.routes.js
server.mjs
swagger/swagger_output.json
utils/notificationWsUtils.js

adde changes

---

routes/user/order.routes.js
swagger/swagger_output.json

change 3543

---

controllers/groupchat/groupchat.controllers.js
controllers/groupchat/members.controllers.js

[chore] added filter to group members

[chore] added filter to group members

---

controllers/groupchat/messages.controllers.js
routes/groupchat/messages.routes.js

[chore] added send message

---

controllers/chats/messages.controllers.js
controllers/chats/websocket.controllers.js
utils/websocketsUtils.js

[fix]: fixed websocket api

---

controllers/groupchat/websocket.controllers.js
utils/websocketsUtils.js

[fix] fixed websocket for groupchat

[fix] fixed websocket for groupchat

---

config/file.js
controllers/chats/messages.controllers.js
controllers/groupchat/messages.controllers.js
models/groupMessage.model.js
routes/groupchat/messages.routes.js

[feat] added ability to uplaod image and file to groupchat route

[feat] added ability to uplaod image and file to groupchat route
